// src/config/rolePermissions.ts
import { PERMISSIONS } from "./permissions";
import type { Permission } from "./permissions";

// Lista exacta de roles recibidos del backend
export type Role =
  | "ADMINISTRADOR"
  | "SOPORTE_REMOTO"
  | "SOPORTE_INSITU"
  | "CLIENTE_EMPRESA"
  | "CLIENTE_SUCURSAL";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMINISTRADOR: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE_EMPLOYEE,
    PERMISSIONS.USERS_ASSIGN_ROLE,
    PERMISSIONS.USERS_TOGGLE_STATUS,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_UPDATE_CONTRACT,
    PERMISSIONS.EQUIPMENT_READ,
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_ASSIGN,
    PERMISSIONS.EQUIPMENT_DELETE,
    PERMISSIONS.HARDWARE_INSTALL,
    PERMISSIONS.SOFTWARE_INSTALL,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_TRANSFER,
    PERMISSIONS.TICKETS_RESOLVE,
    PERMISSIONS.TICKETS_METRICS,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_CANCEL,
  ],

  SOPORTE_REMOTO: [
    PERMISSIONS.EQUIPMENT_READ,
    PERMISSIONS.HARDWARE_INSTALL,
    PERMISSIONS.SOFTWARE_INSTALL,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_TRANSFER,
    PERMISSIONS.TICKETS_RESOLVE,
  ],

  SOPORTE_INSITU: [
    PERMISSIONS.EQUIPMENT_READ,
    PERMISSIONS.HARDWARE_INSTALL,
    PERMISSIONS.SOFTWARE_INSTALL,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_RESOLVE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_CREATE,
  ],

  CLIENTE_EMPRESA: [
    PERMISSIONS.EQUIPMENT_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_METRICS,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_CREATE,
  ],

  CLIENTE_SUCURSAL: [
    PERMISSIONS.EQUIPMENT_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ,
  ],
};
